#ifndef QUIC_SRC_STREAM_H_
#define QUIC_SRC_STREAM_H_

#include <tbquic/types.h>


#define TBQUIC_STREAM_INITIATED_BY_SERVER 	0x01
#define TBQUIC_STREAM_UNIDIRECTIONAL        0x02

#define TBQUIC_STREAM_CLIENT_INITIATED_BIDIRECTIONAL 	0
#define TBQUIC_STREAM_SERVER_INITIATED_BIDIRECTIONAL 	TBQUIC_STREAM_INITIATED_BY_SERVER
#define TBQUIC_STREAM_CLIENT_INITIATED_UNIDIRECTIONAL 	TBQUIC_STREAM_UNIDIRECTIONAL
#define TBQUIC_STREAM_SERVER_INITIATED_UNIDIRECTIONAL 	(TBQUIC_STREAM_INITIATED_BY_SERVER|TBQUIC_STREAM_UNIDIRECTIONAL)

enum {
	TBQUIC_STREAM_STATE_READY = 0,
	TBQUIC_STREAM_STATE_SEND,
	TBQUIC_STREAM_STATE_RECV,
	TBQUIC_STREAM_STATE_SIZE_KNOWN,
	TBQUIC_STREAM_STATE_DATA_SEND,
	TBQUIC_STREAM_STATE_DATA_RECVD,
	TBQUIC_STREAM_STATE_RECV_DATA_READ,
	TBQUIC_STREAM_STATE_RECV_RESET_SEND,
	TBQUIC_STREAM_STATE_RECV_RESET_RECVD,
	TBQUIC_STREAM_STATE_RECV_RESET_READ,
};

int QuicConnect(QUIC *);
int QuicAccept(QUIC *);

#endif
