#ifndef TBQUIC_INCLUDE_TBQUIC_CIPHER_H_
#define TBQUIC_INCLUDE_TBQUIC_CIPHER_H_

enum QuicAlgId {
    QUIC_ALG_AES_128_ECB,
    QUIC_ALG_AES_192_ECB,
    QUIC_ALG_AES_256_ECB,
    QUIC_ALG_AES_128_GCM,
    QUIC_ALG_AES_192_GCM,
    QUIC_ALG_AES_256_GCM,
    QUIC_ALG_AES_128_CCM,
    QUIC_ALG_AES_192_CCM,
    QUIC_ALG_AES_256_CCM,
    QUIC_ALG_AES_128_CCM_8,
    QUIC_ALG_CHACHA20,
    QUIC_ALG_CHACHA20POLY1305,
    QUIC_ALG_MAX,
};

#endif
